version: "3.9"

networks:
  docker.network:
    driver: bridge

services:
  php:
    build: ./docker/php
    restart: unless-stopped
    container_name: docker.php
    tty: true
    depends_on:
      - mysql
    networks:
      - docker.network
    volumes:
      - .:/var/www

  apache:
    build: ./docker/apache
    restart: unless-stopped
    container_name: docker.apache
    tty: true
    depends_on:
      - php
    ports:
      - "80:80"
      - "443:443"
    networks:
      - docker.network
    volumes:
      - ./html/your_file:/var/www/html/
      - ./docker/apache/ssl/your_certificate.crt:/etc/ssl/certs/mycert.crt
      - ./docker/apache/ssl/your_key.key:/etc/ssl/private/mycert.key

  mysql:
    image: arm64v8/mysql:latest
    platform: linux/arm64
    restart: unless-stopped
    container_name: docker.mysql
    tty: true
    ports:
      - "3306:3306"
    networks:
      - docker.network
    volumes:
      - "./docker/mysql/dbdata:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-root}
      MYSQL_USER: ${MYSQL_USER:-localhost}

  phpmyadmin:
    image: phpmyadmin
    container_name: docker.phpmyadmin
    tty: true
    depends_on:
      - mysql
    ports:
      - "8080:80"
    networks:
      - docker.network
    environment:
      PMA_HOST: mysql
      PMA_ARBITRARY: 1
      PMA_PORT: 3306
  grafana:
    image: grafana/grafana:latest
    container_name: docker.grafana
    depends_on:
      - mysql
    ports:
      - "3000:3000"
    networks:
      - docker.network
    volumes:
      - ./docker/graphana_data:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD:-admin}
      GF_USERS_ALLOW_SIGN_UP: "false"
      

  
